[phases.setup]
nixPkgs = ['nodejs', 'python39']

[phases.install]
cmds = [
  'python -m pip install -r requirements.txt',
  'npm install'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'python main.py'