[phases.setup]
nixPkgs = ['nodejs', 'python39', 'pip']

[phases.install]
cmds = [
  'pip install -r requirements.txt',
  'npm install'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'python main.py'